<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CA020705Z2" failures="1" tests="5" name="Firefox Test" time="0.073" errors="0" timestamp="13 May 2020 05:45:55 GMT">
  <testcase classname="testng.NewTest" name="tc05" time="0.026"/>
  <testcase classname="testng.NewTest" name="tc04" time="0.002">
    <failure type="java.lang.AssertionError" message="testcase fail">
      <![CDATA[java.lang.AssertionError: testcase fail
	at testng.NewTest.tc04(NewTest.java:27)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tc04 -->
  <testcase classname="testng.NewTest" name="tc03" time="0.002"/>
  <testcase classname="testng.NewTest" name="tc02" time="0.001"/>
  <testcase classname="testng.NewTest" name="tc01" time="0.001"/>
</testsuite> <!-- Firefox Test -->
